# render.yaml
static:
  headers:
    /:
      - key: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self';"
  routes:
    - type: rewrite
      source: /*
      destination: /index.html
